version: "3.4"

services:
  reverse-proxy:
    container_name: reverse-proxy
    build: ./Nginx
    networks:
      - nginx-network
    ports:
      - 20000:80

  myapi:
    image: ${DOCKER_REGISTRY-}myapi
    build:
      context: .
      dockerfile: MyApi/Dockerfile
    depends_on:
      - reverse-proxy
    networks:
      - nginx-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 20001:80

networks:
  nginx-network:
    driver: "bridge"
